using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using TaskFlow.Utility;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.Compilation;
using UnityEngine;

namespace TaskFlow.Editor
{
    /// <summary>
    /// 扫描所有 Signal 子类，自动生成封闭泛型 Channel 子类。
    /// 启动 / 编译重载 / 点击刷新 时自动执行；也可通过菜单手动执行。
    /// </summary>
    internal static class SignalChannelGenerator
    {
        private const string OutputDir = "Assets/TaskFlow/Generated";
        private const string Namespace = "TaskFlow.Generated";
        private const string MarkerTag = "<TaskFlow:auto-generated>"; // 用于识别本工具生成的文件

        /// <summary>
        /// 脚本编译重载完成后自动触发（含编辑器启动、点击 Refresh 触发的编译）。
        /// 由于有内容比对保护，无变化时不会再次引发编译循环。
        /// </summary>
        [DidReloadScripts]
        private static void OnScriptsReloaded() => GenerateAll();

        [MenuItem("TaskFlow/Generate Signal Channels")] // Ctrl/Cmd + Shift + G
        private static void GenerateFromMenu() => GenerateAll();

        private static void GenerateAll()
        {
            try
            {
                if (!Directory.Exists(OutputDir))
                    Directory.CreateDirectory(OutputDir);

                // 收集有效信号子类
                var signalTypes = TypeCache.GetTypesDerivedFrom<Signal>()
                    .Where(t => !t.IsAbstract && !t.IsInterface && !t.IsGenericTypeDefinition)
                    .ToList();

                bool dirty = false;

                // 1. 清理已删除 Signal 对应的过期生成文件
                dirty |= CleanObsolete(signalTypes);

                // 2. 为每个 Signal 子类生成一个 Channel 封闭泛型文件
                foreach (var signal in signalTypes)
                    dirty |= WriteChannelFile(signal);

                if (!dirty)
                    return; // 无任何变更，不刷新，避免编译循环

                // 3. 保存资产 + 刷新资源库 + 强制触发一次脚本重新编译
                AssetDatabase.SaveAssets();
                AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate);
                CompilationPipeline.RequestScriptCompilation();

                Debug.Log($"[TaskFlow] Signal Channel 生成完毕 ({signalTypes.Count} 个)，已触发保存与编译。");
            }
            catch (System.Exception e)
            {
                Debug.LogError($"[TaskFlow] Signal Channel 生成失败：{e}");
            }
        }

        // ---------------------------- 核心逻辑 ----------------------------

        private static bool WriteChannelFile(System.Type signal)
        {
            string fileName = MakeSafeClassName(signal);
            string filePath = Path.Combine(OutputDir, fileName + ".cs");
            string code = BuildTemplate(signal, fileName);

            // 内容未变化则跳过（防止重载→生成→再编译的无限循环）
            if (File.Exists(filePath) && File.ReadAllText(filePath) == code)
                return false;

            File.WriteAllText(filePath, code, new UTF8Encoding(false)); // UTF8 无 BOM
            Debug.Log($"[TaskFlow] 已生成 Channel：{filePath}  →  {fileName} : Channel<{signal.Name}>");
            return true;
        }

        private static bool CleanObsolete(List<System.Type> signalTypes)
        {
            var validNames = new HashSet<string>(signalTypes.Select(MakeSafeClassName));
            bool removed = false;

            foreach (var file in Directory.GetFiles(OutputDir, "*.cs"))
            {
                // 只删除本工具生成的文件，不动手写文件
                if (!File.ReadAllText(file).Contains(MarkerTag)) continue;

                string name = Path.GetFileNameWithoutExtension(file);
                if (validNames.Contains(name)) continue;

                File.Delete(file);
                if (File.Exists(file + ".meta")) File.Delete(file + ".meta");
                Debug.Log($"[TaskFlow] 删除过期 Channel：{file}");
                removed = true;
            }
            return removed;
        }

        private static string BuildTemplate(System.Type signal, string className)
        {
            return $@"// {MarkerTag}
// <auto-generated>
//   此文件由 TaskFlow 编辑器工具自动生成，请勿手工修改。
//   来源信号类型：{signal.AssemblyQualifiedName}
// </auto-generated>

using UnityEngine;
namespace {Namespace}
{{
    /// <summary>{signal.Name} 对应的封闭泛型通道。</summary>
    [CreateAssetMenu(fileName = ""{className.SplitCamelCase()}"", menuName = ""TaskFlow/Channel/{className.SplitCamelCase()}"")]
    public sealed class {className} : global::TaskFlow.Channel<{TypeRef(signal)}>
    {{
#if UNITY_EDITOR
        [global::UnityEngine.ContextMenu(""Create Channel Asset in Resources"")]
#endif
        private void _KeepAlive() {{ }}
    }}
}}
";
        }

        // --------------------------- 命名辅助 ---------------------------

        /// <summary>安全的类名：基于类型完整名（含嵌套），避免不同命名空间同名冲突。</summary>
        private static string MakeSafeClassName(System.Type t)
            => Sanitize(FriendlyFullName(t)) + "Channel";

        /// <summary>生成 C# 中可用的类型引用表达式，正确处理嵌套类型 Outer+Inner → Outer.Inner。</summary>
        private static string TypeRef(System.Type t)
        {
            var parts = new Stack<string>();
            var root = t;
            while (root.IsNested)
            {
                parts.Push(root.Name);
                root = root.DeclaringType;
            }
            parts.Push(root.Name);

            return string.IsNullOrEmpty(root.Namespace)
                ? string.Join(".", parts)
                : $"global::{root.Namespace}.{string.Join(".", parts)}";
        }

        private static string FriendlyFullName(System.Type t)
        {
            var parts = new Stack<string>();
            while (t != null)
            {
                parts.Push(Sanitize(t.Name));
                t = t.DeclaringType;
            }
            return string.Join("_", parts);
        }

        private static string Sanitize(string s)
        {
            var sb = new StringBuilder(s.Length);
            foreach (var c in s)
            {
                if (char.IsLetterOrDigit(c) || c == '_') sb.Append(c);
                else sb.Append('_'); // ` + . 空格 等非法字符一律替换为 _
            }
            if (sb.Length > 0 && char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }
    }
}
